services:
  takaro-mcp:
    image: ghcr.io/gettakaro/mcp:0.0.3
    ports:
      - "18000:3000"
    environment:
      - HOST=0.0.0.0
    env_file:
      - .env
    restart: unless-stopped

  mock-gameserver:
    image: ghcr.io/gettakaro/takaro-app-mock-gameserver:latest
    ports:
      - "3002:3002"
    environment:
      - T_WS_URL=wss://connect.takaro.io
      - MOCK_SERVER_NAME=Local Mock Server
      - MOCK_SIM_AUTO_START=true
    env_file:
      - .env
    restart: unless-stopped